#!/usr/bin/env python

from pathlib import Path
from zensols.cli import ConfigurationImporterCliHarness

if (__name__ == '__main__'):
    out_file: Path = Path('target/lat')
    out_file.mkdir(parents=True, exist_ok=True)
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.datdesc.ApplicationFactory',
        proto_args=f'test-resources/config {out_file}',
        proto_factory_kwargs={'reload_pattern': r'^zensols.datdesc'},
    )
    harness.run()
