notestabdef:
  type: one_column_slack
  path: test-resources/csv/note-events.csv
  caption: Annotated medical notes by category and their distribution in the annotation set.
  uses: booktabs
  hlines: [5]
  percent_column_names: ['Proportion']
  params:
    size: \footnotesize

notestabcolone:
  type: slack
  slack_column: 1
  type: one_column_slack
  path: test-resources/csv/note-events.csv
  caption: Annotated medical notes by category and their distribution in the annotation set.
  uses: booktabs
  hlines: [5]
  percent_column_names: ['Proportion']
  params:
    placement: h!
